services:

    casebox_core.service_auth.authentication:
        class: Casebox\CoreBundle\Service\Auth\CaseboxAuth
        arguments: [ "@service_container" ]

    casebox_core.service.user:
        class: Casebox\CoreBundle\Service\User
        arguments: [ "@service_container" ]

    casebox_core.service.db:
        class: Casebox\CoreBundle\Service\DBService
        calls:
            - [setContainer, [ "@service_container" ]]

    casebox_core.service_state.dbprovider:
        class: Casebox\CoreBundle\Service\State\DBProvider

    casebox_core.service.redis_service:
        class: Casebox\CoreBundle\Service\RedisService
        arguments: [ "@service_container" ]

    casebox_core.service_auth.two_step_auth:
        class: Casebox\CoreBundle\Service\Auth\TwoStepAuth
        calls:
            - [setContainer, [ "@service_container" ] ]

    casebox_core.service.users_groups:
        class: Casebox\CoreBundle\Service\UsersGroups

    casebox_core.service_objects.object:
        class: Casebox\CoreBundle\Service\Objects\Object

    casebox_core.service.styles_service:
        class: Casebox\CoreBundle\Service\StylesService
        calls:
            - [setTwig, ['@twig']]

    casebox_core.service.javascript_service:
        class: Casebox\CoreBundle\Service\JavascriptService
        calls:
            - [setTwig, ['@twig']]

    casebox_core.service.objects:
        class: Casebox\CoreBundle\Service\Objects

    casebox_core.service.minify:
        class: Casebox\CoreBundle\Service\Minify
        arguments: [ "@service_container" ]

    casebox_core.service.web_dav_service:
        class: Casebox\CoreBundle\Service\WebDavService
        calls:
            - [setContainer, ['@service_container']]
